name: coverage
on:
  push:
    branches: [main]

jobs:
  update-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: astral-sh/setup-uv@v6
      with:
        version: '>=0.7'
        python-version: 3.9
    - name: Setup
      run: |
        uv sync --locked
    - name: Run coverage
      run: |
        coverage run -m pytest
        # .coverage.* files are ignored by git
        coverage report -m | tee .coverage.out
        percent=$(grep -E '^TOTAL\s.+\s[0-9]{1,3}%$' .coverage.out \
                  | awk '{gsub("%$", "", $NF); print($NF)}')
        python scripts/make-coverage-badge.py -o .coverage.svg "$percent"
    - name: Update coverage badge
      env:
        COVERAGE_BADGE_BRANCH: coverage-badge
      run: |
        git config --global user.email "devops@dimagi.com"
        git config --global user.name "$GITHUB_ACTOR"
        bash scripts/update-coverage-badge.sh "$COVERAGE_BADGE_BRANCH"
