name: coverage
on:
  push:
    branches: [main]

jobs:
  update-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup
      run: |
        python --version
        pip install --upgrade pip wheel
        pip install django pynose coverage
    - name: Run coverage
      run: |
        # .coverage.* files are ignored by git
        pynose --with-coverage --cover-erase --cover-package=field_audit | tee .coverage.out
        percent=$(grep -E '^TOTAL\s.+\s[0-9]{1,3}%$' .coverage.out \
                  | awk '{gsub("%$", "", $NF); print($NF)}')
        python scripts/make-coverage-badge.py -o .coverage.svg "$percent"
    - name: Update coverage badge
      env:
        COVERAGE_BADGE_BRANCH: coverage-badge
      run: |
        git config --global user.email "devops@dimagi.com"
        git config --global user.name "$GITHUB_ACTOR"
        bash scripts/update-coverage-badge.sh "$COVERAGE_BADGE_BRANCH"
